version: '3.8'

services:
  chat:
    ports:
      - "5000:5000"
    env_file:
      - .env
    entrypoint: ["uvicorn", "app.run:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]

    volumes: 
      - .:/app
    stdin_open: true
    tty: true
