version: '3.8'

services:
  chat:
    container_name: chat
    restart: always
    env_file:
      - .env
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - chat-db

  chat-db:
    container_name: chat-db
    image: postgres:13.4
    env_file:
      - .env
    volumes:
      - chat-db:/var/lib/postgresql/data

volumes:
  chat-db:
    driver: local
